services:
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: moleculer
      POSTGRES_PASSWORD: m013cu13r
      POSTGRES_DB: core